iamproperty/iamproperty.github.io

- package.json
1. Changed paths to allow svgs to display
1. a
2. b
3. c
> Changed paths to allow svgs to display

- .github/workflows/release-package.yml
- docs/views/standalone/IamsoldAdmin.vue
- docs/views/standalone/PrintExample.vue
- docs/views/standalone/PrintExampleSingle.vue
- src/index.js
> Feg 3/feature/update technical info

- docs/views/Changelog.vue
- index.html
- package.json
1. Install GA
2. Update version number
> Install GA

- assets/sass/components/applied-filters.scss
- assets/ts/components/applied-filters/applied-filters.component.ts
- assets/ts/modules/applied-filters.ts
- docs/routes.ts
- docs/views/standalone/AgentDashboard.vue
1. a
2. b
3. c
- /page
FEG-999
> applied filters setup

- assets/sass/components/dialog.scss
- assets/ts/modules/table.ts
- docs/views/standalone/AgentDashboard.vue
1. a
2. b
3. c
- /page
FEG-999
> Improve the filters

- assets/sass/components/card.scss
- docs/views/components/CardDoc.vue
1. Change CSS for default card's optional icon so it doesn't change on hover
- /components/card
FEG-105
> FEG-105 - CSS Fix card .scss

- assets/sass/components/table.scss
- assets/sass/foundations/reboot.scss
- assets/ts/components/table/table.component.ts
- assets/ts/modules/applied-filters.ts
- assets/ts/modules/table.ts
- assets/ts/tests/table.spec.ts
- data/compliance-dashboard.json
- docs/views/Changelog.vue
- docs/views/standalone/ComplianceDashboard.vue
- package.json
1. a
2. b
3. c
- /page
FEG-999
> Feg 106/bug/table styling

- assets/sass/components/table.scss
- assets/ts/modules/table.ts
- data/compliance-dashboard.json
- docs/views/standalone/ComplianceDashboard.vue
1. Allow for the endpoint schema to be configurable so it can support different setups
2. Fix a couple of small style issues
- /standalone/compliance-dashboard
FEG-107
> Feg 107/bug/better ajax support tables

- assets/sass/components/table.scss
- assets/ts/modules/table.ts
- docs/views/Changelog.vue
- package.json
1. Update to tables
- /page
FEG-110
> Table updates

- assets/sass/components/dialog.scss
- assets/sass/components/pagination.scss
- assets/sass/components/table.scss
- assets/ts/components/table/table.component.ts
- assets/ts/modules/table.ts
- docs/views/Changelog.vue
- package.json
- rollup.config.js
1. a
2. b
3. c
- /page
FEG-999
> Small fixes

- assets/sass/components/dialog.scss
- assets/sass/components/pagination.scss
- assets/sass/components/table.scss
- assets/ts/components/table/table.component.ts
- assets/ts/modules/table.ts
- docs/views/Changelog.vue
- package.json
- rollup.config.js
> Release v3.7.3

- assets/sass/components/container.scss
- assets/ts/modules/table.ts
1. Pagination scroll to top of table after clicking button
N/A
FEG-124
> FEG-124 - Pagination scroll to top of table after clicking button

- assets/sass/components/table.scss
1. Update the alert icon on the table
N/A
FEG-125
> FEG-125 Update table.scss

- assets/sass/foundations/buttons.scss
1. Make sure buttons are always bold
- /components/buttons
FEG-122
> FEG-122 Update buttons.scss

- assets/ts/components/pagination/pagination.component.ts
- assets/ts/components/table/table.component.ts
- assets/ts/modules/table.ts
1. Move data attributes to the connected callback
N/A
FEG-148
> FEG-148 More attributes

- assets/ts/components/table/table.component.ts
- docs/views/Changelog.vue
- package.json
- src/components/Table/Table.vue
1. Moving creating classes to the connected callback
N/A
FEG-150
> Fix classes not being defined

- assets/sass/components/table.scss
- assets/ts/modules/table.ts
- docs/views/foundations/Icons.vue
1. Add additional table status'
- /foundations/icons
FEG-156
> Add additional table status

- assets/sass/components/dialog.scss
- docs/App.vue
- docs/routes.ts
- docs/views/Search.vue
1. Add in search functionality to the design system
- /search
FEG-165
> Add in search functionality

- assets/ts/modules/data-layer.md
- assets/ts/modules/data-layer.ts
- assets/ts/tests/data-layer.spec.js
1. Data layer function optimised
2. Unit tests added for data layer function
3. Documentation added for the datalayer function
N/A
FEG-158
> Feg 158/feature/improve codes using chatgpt

- assets/ts/modules/dialogs.ts
- assets/ts/modules/inputs.ts
1. a
2. b
3. c
- /page
FEG-999
> bug fixing

- assets/ts/components/accordion/README.md
- assets/ts/components/applied-filters/README.md
- assets/ts/components/card/README.md
- assets/ts/components/fileupload/README.md
- assets/ts/components/filterlist/README.md
- assets/ts/components/header/README.md
- assets/ts/components/notification/README.md
- assets/ts/components/pagination/README.md
- assets/ts/components/table/README.md
- assets/ts/components/tabs/README.md
- src/components/Card/Card.vue
1. Updated the readme files to include installation info for components
N/A
FEG-187
> Feg 187/feature/update docs with comp install code

- assets/ts/modules/dialogs.ts
- docs/views/Changelog.vue
- package.json
1. Move code into createDialog function so its can be used programmatically
N/A
FEG-210
> Move code into create function

- assets/sass/components/forms.scss
1. Expand error messages to include selects
N/A
FEG-230
> FEG-230 Expand error messages to include selects

- docs/views/ModalVariants.vue
1. Fixes the Multi-step and Acknowledgement modal variant labels
> Correct modal variant labels

- assets/sass/components/dialog.scss
- docs/views/components/ModalDoc.vue
1. Add a break into the dialog to match design
2. Fix the button size
3. Fix the weird fade problem
- /components/modal (transactional model)
FEG-250
> Update transactional dialog

- src/index.js
> Release 4 fix

- assets/sass/components/actionbar.scss
- assets/sass/components/admin-panel.scss
- assets/ts/components/table/table.component.ts
- docs/views/examples/ActionbarPanel.vue
- docs/views/examples/Index.vue
1. Actionbar in an admin panel example page
- /examples/actionbar-panel
FEG-242
> Actionbar in an admin panel

- assets/sass/components/forms.scss
- assets/ts/modules/dialogs.ts
- docs/views/components/ModalDoc.vue
- package.json
1. Fix bug that stops the developer from adding there own button into the form of the multi step modal
- /components/modal
FEG-254
> Feg 254/bug/multi step modal submit btn

- assets/sass/components/address-lookup.scss
- assets/ts/components/address-lookup/address-lookup.component.ts
- assets/ts/modules/dynamicEvents.ts
- docs/views/components/AddressLookupDoc.vue
- docs/views/standalone/crm-mb/Page5.vue
- rollup.config.js
1. Improve the address lookup
- /standalone/crm-mb/page5
FEG-290
> Feg 290/feature/improve address lookup

- assets/sass/components/actionbar-global.scss
- assets/sass/components/actionbar.scss
- assets/sass/components/table.extras.scss
- assets/sass/components/table.scss
1. Minor CSS amends
- /components/table
FEG-285
> Minor table fixes

- assets/sass/elements/forms.scss
- assets/sass/elements/table.element.scss
- docs/App.vue
- docs/views/foundations/Colours.vue
- docs/views/foundations/DynamicEvents.vue
1. Minor CSS amends
N?A
FEG-149
> Help with the display of tables in the docs

- assets/sass/elements/forms.scss
- assets/ts/modules/inputs.ts
- docs/App.vue
- docs/main.ts
- docs/views/form/Date.vue
1. Add support for adding min and max dates via JS
2. Custom date validation for allowing certain days
- /form/date
FEG-303
> Add date validation

- assets/sass/components/nav.global.scss
- assets/sass/elements/forms.scss
- assets/ts/components/address-lookup/address-lookup.component.ts
- assets/ts/components/nav/README.md
- assets/ts/components/nav/nav.component.ts
- assets/ts/components/search/search.component.ts
- assets/ts/modules/dynamicEvents.ts
- assets/ts/modules/helpers.ts
- assets/ts/modules/table.ts
- docs/App.vue
- docs/routes.ts
- docs/views/components/AddressLookupDoc.vue
- docs/views/components/SearchDoc.vue
- package.json
- public/addressess2.json
- public/existing.json
- public/iamsold.json
- rollup.config.js
- src/components/Nav/README.md
- src/components/Search/Search.vue
1. Add new component
2. Update the nav component to remove all search functionality and allow for the new component to be added
- /components/search
FEG-310
> Added new search component

- assets/sass/elements/forms.scss
- package.json
1. Add !important to some rules
- /page
FEG-319
> Feg 319/bug/select overlapping text

- assets/sass/_func.scss
- assets/sass/elements/forms.scss
- assets/ts/modules/inputs.ts
- docs/views/form/FormInputDoc.vue
- package.json
1. a
2. b
3. c
- /page
FEG-999
> optional text

- assets/sass/components/card.scss
- assets/ts/components/card/card.component.ts
- docs/views/components/CardDoc.vue
- package.json
1. New dashboard card components
- /components/card #Dashboard card (BETA)
FEG-329
> New card component

- assets/sass/components/nav.global.scss
- assets/sass/components/nav.scss
- assets/sass/elements/buttons.scss
- assets/sass/elements/dialog.scss
- assets/sass/elements/icons.scss
- assets/ts/components/nav/nav.component.ts
- assets/ts/components/search/search.component.ts
- docs/views/standalone/Agent.vue
- package.json
1. a
2. b
3. c
- /page
FEG-999
> Update nav prototype

- assets/sass/elements/dialog.scss
- assets/ts/modules/dialogs.ts
- assets/ts/modules/helpers.ts
- docs/views/dialogs/ModalDoc.vue
- package.json
- src/components/Card/Card.vue
- src/components/Table/Table.vue
1. Update the model selectros
- /dialogs/modal
FEG-FEG-330
> Change the model selectors

- assets/sass/components/table.global.scss
- docs/views/elements/Icons.vue
1. New status' added
2. Updated the docs
- /elements/icons
FEG-386
> FEG-386 - Add a new status type

- assets/sass/_functions/variables.scss
- assets/sass/foundations/root.scss
- docs/views/foundations/Colours.vue
1. Update the light colour when in dark mode
- /page
FEG-413
> Update the light colour

- assets/sass/elements/progress.scss
- assets/ts/modules/helpers.ts
- docs/App.vue
- docs/views/elements/ProgressDoc.vue
1. Circular progress bar beta
- /elements/progress
FEG-421
> Circular progress

- assets/ts/components/actionbar/actionbar.component.ts
- assets/ts/components/card/card.component.ts
- assets/ts/components/carousel/carousel.component.ts
- assets/ts/components/fileupload/fileupload.component.ts
- assets/ts/components/filterlist/filterlist.component.ts
- assets/ts/components/inline-edit/inline-edit.component.ts
- assets/ts/components/multiselect/multiselect.component.ts
- assets/ts/components/notification/notification.component.ts
1. Add CSS parts into components
- N/A
FEG-443
> Add parts into components

- assets/sass/components/barchart.component.scss
- assets/sass/components/charts.module.scss
- assets/sass/elements/admin-panel.scss
- assets/ts/components/barchart/barchart.component.ts
- docs/views/form/Date.vue
- package.json
1. a
2. b
3. c
- /page
FEG-999
> charts fixes

- assets/ts/modules/chart.module.ts
1. a
2. b
3. c
- /page
FEG-999
> Release 6 fix

- assets/sass/components/multiselect.preload.scss
- assets/sass/elements/badge-tag.scss
- assets/sass/elements/forms.scss
- docs/views/form/Date.vue
1. a
2. b
3. c
- /page
FEG-999
> Minor changes

- assets/sass/elements/buttons.scss
1. Update the CSS
- /elements/buttons
FEG-511
> Make sure the before has content set

- assets/sass/_elements.scss
- assets/sass/elements/forms.scss
- assets/sass/elements/toggle-button.scss
- docs/views/form/Toggle.vue
1. Moved the market appraisal toggle button CSS over into design system
- /form/toggle
FEG-135
[ ] Has the pull request npm task been ran?
This will run the unit tests, lint the repo, run prettier and audit the file sizes.
> Toggle button prototype

- docs/App.vue
- docs/events.js
- docs/routes.ts
- docs/views/DataLayer.vue
- docs/views/cards/CardDoc.vue
- docs/views/cards/FilterCardDoc.vue
- docs/views/cards/VideoCardDoc.vue
- docs/views/components/ActionbarDoc.vue
- docs/views/components/BentoGridDoc.vue
- docs/views/components/CarouselDoc.vue
- docs/views/components/File.vue
- docs/views/components/InlineEdit.vue
- docs/views/components/MenuDoc.vue
- docs/views/components/Tables.vue
- docs/views/components/TabsDoc.vue
1. a
2. b
3. c
- /page
FEG-999
[ ] Has the pull request npm task been ran?
This will run the unit tests, lint the repo, run prettier and audit the file sizes.
> Feature/feg 677/data layer docs
