iamproperty/iamproperty.github.io

assets/sass/components/card.scss
assets/sass/components/dialog.scss
assets/ts/components/card/card.component.ts
assets/ts/modules/helpers.ts
docs/views/Changelog.vue
docs/views/components/CardDoc.vue
docs/views/components/DialogDoc.vue
package-lock.json

1. Dialog component
- Improved style of Dialog component (max width, height and responsive)
- Updated dialog documentation page with above changes
- Fixed close icon repeatedly adding to dialog
2. Card component 
- Improved styling when FA icon is used
- Updated card documentation page with above changes
- Changed query selector to `.fa` instead of unnecessary `.icon`
- /components/dialog
- /components/card
FEG-53

FEG-53/feature/update modal page

---

assets/ts/modules/dialogs.ts
audit.json

1. When the dialog is fixed it could dip under the viewport so this JS adds a CSS transform when needed
- /standalone/openview
FEG-103

Feg 103/bug/out of viewport popover

---

assets/ts/components/table/table.component.ts
assets/ts/modules/dialogs.ts
audit.json

1. Remove active states on buttons for the popovers
- /standalone/openview
FEG-102

Feg 102/bug/sticky active state buttons

---

assets/sass/components/dialog.scss

1. Updated dialog CSS to use media query instead of container query which was causing issues
- /components/modal
FEG-138

FEG-138/bug/flexible-widths-dialogs

---

assets/ts/modules/table.ts

Aways update the cta width even if already set
1. Aways update the cta width even if already set
N/A
FEG-151

FEG-151 Update table.ts

---

assets/sass/components/forms.scss
assets/ts/modules/dialogs.ts
docs/views/standalone/ComplianceDashboard.vue
src/components/Table/Table.vue

1. Add in a new tick list radio input variant to use within the sort by dialog
- /standalone/compliance-dashboard
FEG-172

Tick list radio variant for sort by dialog

---

assets/sass/components/dialog.scss
docs/views/components/ModalDoc.vue

1. Allow for the icon to be updated by adding own i element
- /components/modal (transactional modal)
FEG-212

Add own icon

---

assets/sass/components/nav-global.scss
assets/ts/components/card/card.component.ts
assets/ts/modules/applied-filters.ts
assets/ts/modules/dialogs.ts
assets/ts/modules/table.ts
docs/views/standalone/ComplianceDashboard.vue

1. Allow for duplicate filter cards
2. Fix clear filters 
- /standalone/compliance-dashboard
FEG-258

Feg 258/bug/filter cards duplicate in dialog

---

assets/sass/_corefiles.scss
assets/sass/_func.scss
assets/sass/_functions/mixins.scss
assets/sass/components/admin-panel.scss
assets/sass/components/card.scss
assets/sass/components/charts.scss
assets/sass/components/collapsible-side.scss
assets/sass/components/dialog.scss
assets/sass/components/fileupload.scss
assets/sass/components/nav-global.scss
assets/sass/components/nav.scss
assets/sass/components/notification.scss
assets/sass/core.scss
assets/sass/error.scss
assets/sass/foundations/root.scss
assets/sass/main.scss
docs/assets/styles.scss

1. Add the ability to remove dark mode support
N/A
FEG-261

Add the ability to remove dark mode

---

assets/sass/components/actionbar.scss
assets/sass/components/card-global.scss
assets/sass/components/dialog.scss
assets/sass/components/forms.scss
assets/ts/modules/dialogs.ts

1. wrap @supports around CSS that wont work without :has support
N/A
FEG-266

wrap @supports around CSS that wont work without :has support

---

assets/sass/components/collapsible-side.scss
assets/sass/components/dialog.scss
assets/sass/components/forms.scss
assets/sass/components/nav-global.scss
assets/sass/components/nav.scss
assets/sass/components/stepper.scss
assets/sass/components/table.extras.scss
assets/sass/foundations/buttons.scss
assets/ts/components/actionbar/actionbar.component.ts
assets/ts/components/collapsible-side/collapsible-side.component.ts
assets/ts/components/nav/nav.component.ts
assets/ts/modules/carousel.ts
assets/ts/modules/dialogs.ts
assets/ts/modules/table.ts
audit.json
docs/views/standalone/crm-ias/Page2.vue
src/components/Stepper/Step.vue

- Using aria-current=page to style a navigation link differently if it’s the current page. In the case of Vue, the aria-current attribute is added out of the box to the exact current router link. For non SPA examples, this would be added in the same way we add an ‘active’ class currently. 
- Added aria-expanded attribute to the trigger for the collapsible side menu in order to restyle the button depending on it’s state.
- Added aria-expanded to buttons that trigger pop-over lists to restyle the button depending on it’s state.
- Added aria-invalid to form validation CSS so that we can add this attribute when server validation has been performed to restyle the input.
- Applied the ‘selected’ navigation item styles to aria-current=”page”.
- Replaced the use of the selected class to style …

FEG-35-Feature-Using-CSS-to-Enforce-Accessibility

---

assets/sass/components/header.scss
assets/sass/elements/container.scss
assets/sass/foundations/reboot.scss
assets/sass/templates/form.scss
docs/App.vue
docs/views/BestPracticeDoc.vue
docs/views/Changelog.vue
docs/views/DSHeader.vue
docs/views/Home.vue
docs/views/Principles.vue
docs/views/foundations/Colours.vue
src/components/Header/Header.vue

1. Add grid CSS to main element so we dont need container divs anymore
2. Remove some container divs to check the page doesn't break
3. Minor CSS amends
N/A
FEG-302

Add grid CSS to main element so we dont need container divs anymore

---

assets/sass/components/pagination.scss
package.json

1. overriding margin bottom on divs wrapping select boxes
1. Open up the preview site (see the below netlify comment below) and navigate to: /components/pagination
2. The dropdown in the page jump component will be aligned with the 'of x' text
3. The dropdown in the per page dropdown will be aligned with the '/ page' text
FEG-317

FEG 317 - override margin bottom for pagination dropdown wrapper

---

assets/sass/elements/forms.scss
assets/ts/modules/helpers.ts
assets/ts/modules/inputs.ts
assets/ts/vendor/hibp.ts
docs/views/form/FormInputDoc.vue
package.json

1. Add password checker span
2. Configurable min length with a default of 12
3. Create a point based system to rate strength
4. Check that average strength and above passwords dont get returned by the haveibeenpwned api
- /form/inputs (passwords element)
FEG-327

Add a password checker span

---

assets/sass/components/component.native.scss
assets/sass/components/nav.docs.scss
assets/sass/components/nav.global.scss
assets/sass/components/nav.scss
assets/ts/components/nav/nav.component.ts
docs/views/standalone/Agent.vue
docs/views/standalone/Movebutler.vue
package.json
src/components/Nav/Nav.vue
test.html

1. Allow for details menu in pull out menu.
- /standalone/agent
- /standalone/movebutler
FEG-331

Fix to allow for details in the menu component

---

assets/ts/components/address-lookup/address-lookup.component.ts
docs/views/components/AddressLookupDoc.vue
package.json

1. Allow for the manual address lookup to be open using the data attribute [data-manual]
- /components/addresslookup
FEG-389

Feg 389/feature/manual addr lookup

---

assets/sass/elements/forms.scss

1. removed max height from textarea component
2. overrode max height style for textarea
- /form/inputs
FEG-411

FEG-411-removing max height from textarea field

---

docs/views/DialogUsage.vue
docs/views/NotificationsUsage.vue
docs/views/dialogs/DialogDoc.vue
docs/views/dialogs/ModalDoc.vue
docs/views/dialogs/NonModalDoc.vue
docs/views/elements/Media.vue
docs/views/form/FormInputDoc.vue
docs/views/notifications/SystemNotificationsDoc.vue
docs/views/selectionControls.vue

1. Updated links across the documentation to go to the intended pages
2. Fixed a couple of typos
- /page
FEG-441

Fixing broken links across the documentation

---

assets/sass/elements/forms.scss
package.json

1. adding textarea-height-scale variable and set to 3 by default
2. replaced hardcoded value with variable
- /page
FEG-445

adding textarea-height-scale variable and replacing hard coded value

---

assets/sass/components/carousel.scss
assets/ts/modules/carousel.ts
docs/views/components/CarouselDoc.vue

1. updated carousel JS to account for an item count that isn't divisible by the number of items per 'slide'
2. increased width and removed height from pagination controls so that more pips can show
- /components/carousel
- Navigate to the end of the first carousel on the page (item 23 should show)
- the last pagination dot should be highlighted
- clicking the previous button should move 2 items back instead of a full 3, because we don't have an item count divisble by 3. 
FEG-455

Feg 455/bug/issues with carousel pagination not matching up to current slide

---

assets/ts/components/card/card.component.ts
package.json

1. added check for parentNode being of a certain time to avoid JS errors when the parentNode is a div rather than something clickable. 
- /page
FEG-456

Feg 456/bug/remove need for card to be wrapped in a link button or label

---

assets/sass/components/address-lookup.scss
assets/ts/modules/carousel.ts

1. updated navigation on carousel to take into total item counts that aren't divisible by visibleItems
2. updated postcode lookup styles so that focus style is applied.
3. c
- /components/carousel
- Trying different breakpoints, navigate through the carousel using the next and previous arrows, making sure you can access all the slides and the pagination accurately reflects where you are
- Trying different breakpoints, navigate through the carousel using the pagination dots, making sure you can access all the slides and the pagination accurately reflects where you are
FEG-457

Feg 457/bug/carousel pagination when there are 4 items in view not matching up with controls

---

assets/sass/elements/admin-panel.scss
docs/views/elements/PanelDoc.vue

1.  CSS updates to allow for div as first child of admin panel
2.  Added example to admin panel doc page
- /elements/panel
FEG-459

Updating admin panel css to allow for buttons in header

---

assets/sass/elements/forms.scss
docs/views/form/FormInputDoc.vue

1. Force the CSS of the color inputs using importants
2. Update the docs to test if it works when in a span
- /page
FEG-999

Fix the colour input type

---

assets/ts/components/table/table.component.ts
docs/views/components/ActionbarDoc.vue

1. Add the ability to pre-select input checkboxes in tables.
- /components/actionbar (States section)
FEG-558

Add the ability to pre-select input checkboxes in tables.

---

assets/sass/components/barchart.component.scss
assets/sass/components/charts.module.scss
assets/ts/modules/chart.module.ts
docs/views/charts/BarChart.vue

1. Add menus to the bar charts
2. Include the button and link css to the charts
- /charts/barchart - section Stacked bar with menu
FEG-578 

Add the choice to have menus in the bar charts
